# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alpha2code', models.CharField(max_length=2, unique=True)),
                ('alpha3code', models.CharField(max_length=3, unique=True)),
                ('numericcode', models.CharField(max_length=3, unique=True)),
                ('latitudeavg', models.FloatField()),
                ('longitudeavg', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LocChangeIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changecode', models.CharField(max_length=1, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LocFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locfunction', models.CharField(max_length=1, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Locode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locodecountry', models.CharField(max_length=2)),
                ('locodeplace', models.CharField(max_length=3)),
                ('locname', models.CharField(max_length=100)),
                ('locnamewodia', models.CharField(max_length=100)),
                ('locsubdivision', models.CharField(max_length=3)),
                ('locfunction', models.CharField(max_length=8)),
                ('locdate', models.CharField(max_length=4)),
                ('lociata', models.CharField(max_length=3)),
                ('locoordinates', models.CharField(max_length=12)),
                ('locremarks', models.CharField(max_length=100)),
                ('locode', models.CharField(max_length=5)),
                ('locversion', models.CharField(max_length=10)),
                ('locchangeindicator', models.ForeignKey(blank=True, on_delete=models.SET(''), related_name='+', to='unlocode.LocChangeIndicator')),
            ],
        ),
        migrations.CreateModel(
            name='LocStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locstatus', models.CharField(max_length=2, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level1', models.CharField(max_length=6)),
                ('level2', models.CharField(max_length=6)),
                ('shortcode', models.CharField(max_length=3)),
                ('alpha2code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlocode.Country', to_field='alpha2code')),
            ],
        ),
        migrations.AddField(
            model_name='locode',
            name='locstatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlocode.LocStatus'),
        ),
    ]
