# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlocode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locode',
            name='locchangeindicator',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='locode',
            name='locversion',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
