# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlocode', '0003_auto_20160129_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='locchangeindicator',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='locfunction',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='locstatus',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
