# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlocode', '0005_auto_20160129_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdivision',
            name='level1',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='level2',
            field=models.CharField(max_length=8),
        ),
    ]
