# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlocode', '0007_auto_20160129_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocChangeTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changetag', models.CharField(max_length=5, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
