# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unlocode', '0008_locchangetags'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha2code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LocSubdivison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha2code', models.CharField(max_length=2)),
                ('shortcode', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LocVersion',
            fields=[
                ('version', models.CharField(max_length=6, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='locode',
            name='locversion',
        ),
        migrations.AlterField(
            model_name='locode',
            name='locchangeindicator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='unlocode.LocChangeIndicator', to_field='changecode'),
        ),
        migrations.AlterField(
            model_name='locode',
            name='locstatus',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='unlocode.LocStatus', to_field='statuscode'),
        ),
        migrations.AddField(
            model_name='locsubdivison',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlocode.LocVersion'),
        ),
        migrations.AddField(
            model_name='loccountry',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlocode.LocVersion'),
        ),
        migrations.AddField(
            model_name='locfunction',
            name='version',
            field=models.ForeignKey(default='init', on_delete=django.db.models.deletion.CASCADE, to='unlocode.LocVersion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locode',
            name='version',
            field=models.ForeignKey(default='init', on_delete=django.db.models.deletion.CASCADE, to='unlocode.LocVersion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locstatus',
            name='version',
            field=models.ForeignKey(default='init', on_delete=django.db.models.deletion.CASCADE, to='unlocode.LocVersion'),
            preserve_default=False,
        ),
    ]
