# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlocode', '0009_auto_20160203_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locode',
            name='locchangeindicator',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='locode',
            name='locstatus',
            field=models.CharField(max_length=2),
        ),
    ]
