# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlocode', '0010_auto_20160209_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locode',
            name='locsubdivision',
            field=models.CharField(max_length=5),
        ),
    ]
