# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 14:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('unlocode', '0011_auto_20160209_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='locversion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 9, 14, 3, 49, 47221, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locversion',
            name='creator',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locversion',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 9, 14, 3, 58, 384490, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
