# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlocode', '0012_auto_20160209_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locfunction',
            name='functioncode',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='locstatus',
            name='statuscode',
            field=models.CharField(max_length=2),
        ),
    ]
