# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlocode', '0013_auto_20160211_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locode',
            name='locname',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='locode',
            name='locnamewodia',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='locode',
            name='locode',
            field=models.CharField(db_index=True, max_length=5),
        ),
    ]
