# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unlocode', '0014_auto_20160211_0720'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='loccountry',
            unique_together=set([('version', 'alpha2code')]),
        ),
        migrations.AlterUniqueTogether(
            name='locfunction',
            unique_together=set([('version', 'functioncode')]),
        ),
        migrations.AlterUniqueTogether(
            name='locode',
            unique_together=set([('version', 'locode')]),
        ),
        migrations.AlterUniqueTogether(
            name='locstatus',
            unique_together=set([('version', 'statuscode')]),
        ),
        migrations.AlterUniqueTogether(
            name='locsubdivison',
            unique_together=set([('version', 'alpha2code', 'shortcode')]),
        ),
        migrations.AlterIndexTogether(
            name='loccountry',
            index_together=set([('version', 'alpha2code')]),
        ),
        migrations.AlterIndexTogether(
            name='locfunction',
            index_together=set([('version', 'functioncode')]),
        ),
        migrations.AlterIndexTogether(
            name='locode',
            index_together=set([('version', 'locode')]),
        ),
        migrations.AlterIndexTogether(
            name='locstatus',
            index_together=set([('version', 'statuscode')]),
        ),
        migrations.AlterIndexTogether(
            name='locsubdivison',
            index_together=set([('version', 'alpha2code', 'shortcode')]),
        ),
    ]
