# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unlocode', '0017_auto_20160212_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocSubdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcode', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('alpha2code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlocode.LocCountry')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlocode.LocVersion')),
            ],
        ),
        migrations.AlterField(
            model_name='locode',
            name='locsubdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unlocode.LocSubdivision'),
        ),
        migrations.AlterUniqueTogether(
            name='locsubdivision',
            unique_together=set([('version', 'alpha2code', 'shortcode')]),
        ),
        migrations.AlterIndexTogether(
            name='locsubdivision',
            index_together=set([('version', 'alpha2code', 'shortcode')]),
        ),
    ]
