# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unlocode', '0019_auto_20160212_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locstatus',
            options={'verbose_name_plural': 'LocStatus'},
        ),
        migrations.AlterModelOptions(
            name='locversion',
            options={'get_latest_by': 'version', 'ordering': ['-version']},
        ),
        migrations.DeleteModel(name='LocSubdivison')
    ]
