# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 12:30
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylocation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortTerminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('na2', models.CharField(max_length=2)),
                ('fac_id', models.FloatField()),
                ('na3', models.CharField(max_length=1)),
                ('na3desc', models.CharField(max_length=50)),
                ('pt_id', models.FloatField()),
                ('namdesc', models.CharField(max_length=50)),
                ('na2desc', models.CharField(max_length=50)),
                ('local_name', models.CharField(max_length=7)),
                ('nam', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=6)),
                ('tile_id', models.IntegerField()),
                ('name0', models.CharField(max_length=3)),
                ('f_codedesc', models.CharField(max_length=50)),
                ('f_code', models.CharField(max_length=5)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='WorldBorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips', models.CharField(max_length=2)),
                ('iso2', models.CharField(max_length=2)),
                ('iso3', models.CharField(max_length=3)),
                ('un', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('pop2005', models.IntegerField()),
                ('region', models.IntegerField()),
                ('subregion', models.IntegerField()),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
