# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylocation', '0002_portterminal_worldborder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portterminal',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
