# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylocation', '0003_auto_20160216_1307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortTerminal',
        ),
    ]
