# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 14:32
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylocation', '0005_auto_20160216_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylocation_test',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(default=None, srid=4326),
            preserve_default=False,
        ),
    ]
