# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 15:49
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mylocation', '0006_mylocation_test_mpoly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('area', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylocation.Function')),
            ],
        ),
        migrations.CreateModel(
            name='Unlocode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('locode', models.CharField(max_length=5)),
                ('version', models.CharField(max_length=6)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('country', models.CharField(max_length=50)),
                ('subdivision', models.CharField(max_length=50)),
                ('functions', models.CharField(max_length=8)),
                ('f_port', models.BooleanField(default=False)),
                ('f_rail', models.BooleanField(default=False)),
                ('f_road', models.BooleanField(default=False)),
                ('f_airport', models.BooleanField(default=False)),
                ('f_postal', models.BooleanField(default=False)),
                ('f_multimodal', models.BooleanField(default=False)),
                ('f_fixed', models.BooleanField(default=False)),
                ('f_border', models.BooleanField(default=False)),
                ('lon_dms', models.CharField(max_length=15)),
                ('lat_dms', models.CharField(max_length=15)),
                ('uncoord', models.CharField(max_length=12)),
            ],
        ),
    ]
