# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 13:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mylocation', '0007_function_location_unlocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocodeLocation',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('f_port', models.BooleanField(default=False)),
                ('f_rail', models.BooleanField(default=False)),
                ('f_road', models.BooleanField(default=False)),
                ('f_airport', models.BooleanField(default=False)),
                ('f_postal', models.BooleanField(default=False)),
                ('f_multimodal', models.BooleanField(default=False)),
                ('f_fixed', models.BooleanField(default=False)),
                ('f_border', models.BooleanField(default=False)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylocation.Function')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='location',
            name='code',
        ),
        migrations.AddField(
            model_name='location',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 23, 13, 10, 18, 659083, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 23, 13, 10, 32, 372130, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unlocode',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unlocode',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unlocode',
            name='subdivision',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='locodelocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylocation.Location'),
        ),
        migrations.AddField(
            model_name='locodelocation',
            name='locode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylocation.Unlocode'),
        ),
    ]
