# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 15:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mylocation', '0010_remove_locodelocation_rel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 23, 15, 39, 34, 150783, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='function',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 23, 15, 39, 34, 150783, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
