# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylocation', '0011_auto_20160223_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='creator',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
