# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylocation', '0012_function_creator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mylocation_test',
            new_name='MylocationTest',
        ),
    ]
